export default {
    SET_SINGER: 'SET_SINGER',
    SET_PLAYING: 'SET_PLAYING',
    SET_FULLSCREEN: 'SET_FULLSCREEN',
    SET_PLAYLIST: 'SET_PLAYLIST',
    SET_SEQUENCELIST: 'SET_SEQUENCELIST',
    SET_PLAYMODE: 'SET_MODE',
    SET_CURRENINDEX: 'SET_CURRENINDEX',
    SET_DISC: 'SET_DISC',
    SET_SEARCHHISTORY: 'SET_SEARCHHISTORY'
}